version: '3.7'

services:
  db:
    image: postgres
    restart: always
    container_name: serasa_hotel_db
    ports:
      - 127.0.0.1:${POSTGRES_PORT}:5432
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
      PGUSER: "postgres"
    volumes:
      - ./db/scripts/initdb.sql:/docker-entrypoint-initdb.d/create_tables.sql
    networks:
      srhotel:

  api:
    container_name: serasa_hotel_api
    restart: always
    build: .
    links:
      - db
    depends_on:
      - db
    ports:
      - ${SERVER_PORT}:9000
    volumes:
      - .:/app
    env_file:
      - .env
    networks:
      srhotel:

networks:
  srhotel:
    driver: bridge