version: '3.7'

services:

  db:
    image: postgres
    restart: always
    container_name: serasa_hotel_db
    ports:
      - 5432:5432
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
    volumes:
      - ./db/scripts/initdb.sql:/docker-entrypoint-initdb.d/create_tables.sql
